apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: netdata
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pangarabbit
  source:
    repoURL: "https://netdata.github.io/helmchart/"
    targetRevision: 3.7.94
    chart: netdata
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
